apiVersion: v1
kind: Pod
metadata:
  name: pvc-first-pod
spec:
  containers:
    - name: first-pv-pod
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: volume-with-pvc
          mountPath: /data

  volumes:
    - name: volume-with-pvc
      persistentVolumeClaim:
        claimName: first-sc-pvc

