apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-env-var
spec:
  containers:
    - name: first-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - secretRef:
            name: dp-secret

