apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-files
spec:
  containers:
    - name: second-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: dp-secret-volume
          mountPath: /secret
          readOnly: true

  volumes:
    - name: dp-secret-volume
      secret:
        secretName: dp-secret

