name: Industry CI (Stable)

on:
  push:
    branches:
      - main
      - dev
      - staging
    paths:
      - 'Learnings/CI-CD/11-full-system-industry/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Learnings/CI-CD/11-full-system-industry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push User Service
        run: |
          npm --prefix user-service ci
          npm --prefix user-service test

          docker build -t diwakar5041/user-service:${{ github.sha }} user-service
          docker tag diwakar5041/user-service:${{ github.sha }} diwakar5041/user-service:latest

          docker push diwakar5041/user-service:${{ github.sha }}
          docker push diwakar5041/user-service:latest

      - name: Build & Push Product Service
        run: |
          npm --prefix product-service ci
          npm --prefix product-service test

          docker build -t diwakar5041/product-service:${{ github.sha }} product-service
          docker tag diwakar5041/product-service:${{ github.sha }} diwakar5041/product-service:latest

          docker push diwakar5041/product-service:${{ github.sha }}
          docker push diwakar5041/product-service:latest


      - name: Build & Push API Gateway
        run: |
          npm --prefix api-gateway ci
          npm --prefix api-gateway test

          docker build -t diwakar5041/api-gateway:${{ github.sha }} api-gateway
          docker tag diwakar5041/api-gateway:${{ github.sha }} diwakar5041/api-gateway:latest

          docker push diwakar5041/api-gateway:${{ github.sha }}
          docker push diwakar5041/api-gateway:latest

      - name: Set Environment
        id: env
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ "$BRANCH" == "dev" ]]; then
            echo "file=values-dev.yaml" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "staging" ]]; then
            echo "file=values-staging.yaml" >> $GITHUB_OUTPUT
          else
            echo "file=values-prod.yaml" >> $GITHUB_OUTPUT
          fi

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq


      - name: Update Deployment Repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/diwakar-prakash/DevOps-GitOps-Deployments.git
          cd DevOps-GitOps-Deployments/services/11-full-system-industry

          FILE=${{ steps.env.outputs.file }}

          yq -i ".user.tag = \"${{ github.sha }}\"" $FILE
          yq -i ".product.tag = \"${{ github.sha }}\"" $FILE
          yq -i ".gateway.tag = \"${{ github.sha }}\"" $FILE

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "update image tags to ${{ github.sha }}" || echo "No changes"
          git push