name: Microservices CI

on:
  push:
    branches:
      - main
    paths:
      - 'Learnings/CI-CD/8-multi-micro-storage/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Learnings/CI-CD/8-multi-micro-storage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # USER SERVICE
      - name: Test User Service
        run: |
          npm --prefix user-service ci
          npm --prefix user-service test

      - name: Build & Push User Image
        run: |
          docker build -t diwakar5041/user-service:latest \
                       -t diwakar5041/user-service:${{ github.sha }} user-service
          docker push diwakar5041/user-service:latest
          docker push diwakar5041/user-service:${{ github.sha }}

      # PRODUCT SERVICE
      - name: Test Product Service
        run: |
          npm --prefix product-service ci
          npm --prefix product-service test

      - name: Build & Push Product Image
        run: |
          docker build -t diwakar5041/product-service:latest \
                       -t diwakar5041/product-service:${{ github.sha }} product-service
          docker push diwakar5041/product-service:latest
          docker push diwakar5041/product-service:${{ github.sha }}

      # ORDER SERVICE
      - name: Test Order Service
        run: |
          npm --prefix order-service ci
          npm --prefix order-service test

      - name: Build & Push Order Image
        run: |
          docker build -t diwakar5041/order-service:latest \
                       -t diwakar5041/order-service:${{ github.sha }} order-service
          docker push diwakar5041/order-service:latest
          docker push diwakar5041/order-service:${{ github.sha }}

      # API GATEWAY
      - name: Test API Gateway
        run: |
          npm --prefix app-gateway ci
          npm --prefix app-gateway test

      - name: Build & Push Gateway Image
        run: |
          docker build -t diwakar5041/app-gateway:latest \
                       -t diwakar5041/app-gateway:${{ github.sha }} app-gateway
          docker push diwakar5041/app-gateway:latest
          docker push diwakar5041/app-gateway:${{ github.sha }}

      # UPDATE GITOPS
      - name: Update Helm Values
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/diwakar-prakash/DevOps-GitOps-Deployments.git
          cd DevOps-GitOps-Deployments/services/8-multi-micro-storage || exit 0

          sed -i 's/tag:.*/tag: "${{ github.sha }}"/' values.yaml || true

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push || echo "Nothing to push"


